buildscript {
	repositories {
		mavenCentral()
	}
}



subprojects {

	apply plugin: 'java'
	apply plugin: 'idea'


	java {
		toolchain {
			languageVersion.set(JavaLanguageVersion.of(21))
		}
	}

	repositories {
		mavenCentral()
	}

	compileJava {
		options.encoding = "UTF-8"
	}

	compileTestJava {
		options.encoding = "UTF-8"
	}

	test {
		useJUnitPlatform()
	}

	clean.doFirst {
		delete "${projectDir}/logs/"
		println "${projectDir}/logs/"

		delete "${projectDir}/out/"
		println "${projectDir}/out/"

		delete "${projectDir}/build/"
		println "${projectDir}/build/"
	}

	dependencies {
		// Основные зависимости Lombok
		compileOnly 'org.projectlombok:lombok:1.18.32'
		annotationProcessor 'org.projectlombok:lombok:1.18.32'

		// Зависимости Lombok для тестов
		testCompileOnly 'org.projectlombok:lombok:1.18.32'
		testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
	}

}

