networks:
  timonin-network:
  elastic:
    driver: bridge

services:
  message-broker:
    networks: [ timonin-network ]
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Порт для AMQP (клиенты RabbitMQ)
      - "15672:15672"  # Порт для веб-интерфейса управления

  doc-generator-app:
    networks: [ timonin-network ]
    command: ["./wait-for-it.sh", "message-broker:5672", "--timeout=80", "--", "java", "-jar", "doc-generator.jar"]
    build:
      context: ./my_pr/doc-generator-app
      dockerfile: Dockerfile
    container_name: doc-generator-container
    image: doc-generator:1.0.2
    volumes:
      - ./my_pr/doc-generator-app/docs/proposals:/app/docs/proposals
    ports:
      - "8081:8080"
    depends_on:
      - message-broker

  db:
    image: mysql:8.0
    container_name: mysql-container
    networks:
      - timonin-network
    environment:
      MYSQL_ROOT_PASSWORD: Lalka123
      MYSQL_DATABASE: insurance-calculator-db
    ports:
      - "3306:3306"

  insurance-calculator-app:
    image: insurance-calculator:1.0.2
    build:
      context: ./my_pr/insurance-calculator-app
      dockerfile: Dockerfile
    container_name: insurance-calculator
    volumes:
      - ./my_pr/insurance-calculator/src/main/resources/templates:/app/templates
    networks:
      - timonin-network
    ports:
      - "8080:8080"
    depends_on:
      - message-broker
      - db

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    networks:
      - elastic
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.17.0
    container_name: logstash
    networks:
      - elastic
      - timonin-network
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
