plugins {
	id 'org.springframework.boot' version "3.2.5"
	id 'maven-publish'
}

dependencies {

	implementation('org.springframework.boot:spring-boot-starter-web:3.2.5')

	testImplementation('org.springframework.boot:spring-boot-starter-test:3.2.5')

	test {
		useJUnitPlatform()
	}

}



jar {
		enabled = false
}

bootJar {
		enabled = true
		archiveBaseName = 'insurance-calculator'
		archiveVersion = '1.0.1'
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			// Identify the artifact
			artifact bootJar  // This refers to the Spring Boot's bootJar task

			// Project coordinates
			groupId = 'org.timonin'
			artifactId = 'insurance-calculator'
			version = '1.0.0'

			// Add other metadata as needed
			pom {
				name = 'Insurance Calculator Application'
				description = 'Application to calculate travel insurance premium'
				licenses {
					license {
						name = 'The Apache License, Version 2.0'
						url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
					}
				}
			}
		}
	}

	// Configure the repository location (local Maven repository)
	repositories {
		mavenLocal()
	}
}

