plugins {
	id 'org.springframework.boot' version "3.2.5"
	id 'maven-publish'
	id("com.palantir.docker") version "0.36.0"
//	id 'checkstyle'
}

//checkstyle {
//	configFile = file("config/checkstyle/checkstyle.xml")
//	toolVersion = '10.21.4'
//}

//checkstyleMain {
//	source ='src/main/java'
//}
//checkstyleTest {
//	source ='src/test/java'
//}


dependencies {

	implementation('org.springframework.boot:spring-boot-starter-web:3.2.5')

	testImplementation('org.springframework.boot:spring-boot-starter-test:3.2.5')

	implementation ('org.liquibase:liquibase-core:4.31.0')

	implementation('org.springframework.boot:spring-boot-starter-thymeleaf:3.2.5')


	test {
		useJUnitPlatform()
//		dependsOn checkstyleMain, checkstyleTest
	}

}



jar {
		enabled = false
}

bootJar {
		enabled = true
		archiveBaseName = 'insurance-calculator'
		archiveVersion = '1.0.2'
}

dockerPrepare{
    dependsOn bootJar
}

docker {
    dependsOn bootJar
	name "insurance-calculator:1.0.2"
	files 'build/libs/insurance-calculator-1.0.2.jar'
	buildArgs(['JAR_FILE': "insurance-calculator-1.0.2.jar"])
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			// Identify the artifact
			artifact bootJar  // This refers to the Spring Boot's bootJar task

			// Project coordinates
			groupId = 'org.timonin'
			artifactId = 'insurance-calculator'
			version = '1.0.0'

			// Add other metadata as needed
			pom {
				name = 'Insurance Calculator Application'
				description = 'Application to calculate travel insurance premium'
				licenses {
					license {
						name = 'The Apache License, Version 2.0'
						url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
					}
				}
			}
		}
	}

	// Configure the repository location (local Maven repository)
	repositories {
		mavenLocal()
	}
}

