networks:
  timonin-network:
  elastic:
    driver: bridge

services:
  db:
    networks: [timonin-network]
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Lalka123
      MYSQL_DATABASE: insurance-calculator-db
    ports:
      - "3000:3306"

  insurance-calculator-app:
    networks: [timonin-network]
    container_name: insurance-calculator
    image: insurance-calculator:1.0.2
    ports:
      - "8080:8080"
    depends_on:
      - db

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.17.0
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic
    depends_on:
      - elasticsearch
