# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml


# Thymeleaf template configuration
spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=true

# OpenAPI descriptions (Swagger)
springdoc.api-docs.path=/insurance/travel/api-docs

spring.profiles.active=mysql-container

# Application parameters configuration

medical.risk.limit.level.enabled=true
medical.risk.age.coefficient.enabled=true

agreement.xml.exporter.job.enabled=true
file.export.path=C:/export/agreements
agreement.xml.exporter.job.thread.count=5
