#Datasource configuration (MySQL)
#spring.datasource.url=jdbc:mysql://localhost:3306/java-real-practice-insurance?serverTimezone=Europe/Moscow
#spring.datasource.username=root
#spring.datasource.password=Lalka123
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database=mysql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Datasource configuration (H2)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#spring.h2.console.settings.port=8082


# JPA configuration (MySQL)
# spring.jpa.database=mysql
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA configuration (H2)
#spring.jpa.database=h2
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml


# Thymeleaf template configuration
spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=true


# H2 console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# OpenAPI descriptions (Swagger)
springdoc.api-docs.path=/insurance/travel/api-docs

# Application parameters configuration

medical.risk.limit.level.enabled=true
medical.risk.age.coefficient.enabled=true

tripCancellation.risk.level.enabled=true

agreement.xml.exporter.job.enabled=true
file.export.path=C:/export/agreements

