# Datasource configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/black_list_db
spring.datasource.username=root
spring.datasource.password=Lalka123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA configuration (MySQL)
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8090
